name: TextureAE
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pytorch==1.12.0
  - torchvision==0.13.0
  - setuptools
  - pillow
  - tensorboard
  - tqdm
  - numpy
  - matplotlib
  - imageio